### ISSUE TITLE
Error Message: Delete `␍`eslintprettier/prettier, on windows machine

### ISSUE THREAD

**Issue by rayrunzewang** [BeeQuantAI/platform_api#4]
to stop the error message
find `eslintrc.js` file
put 
 ```
'prettier/prettier': [
      'error',  
      {
        endOfLine: 'auto',   
      },
    ],
```
into
`rules`

**Comment by Chris-Wang** [comment]
Can you provide more information like:
Environment
Steps to Reproduce

Better with screenshot

**Comment by rayrunzewang** [comment]
**Environment and Steps to Reproduce:** once I cloned code to my local windows environment， I met this error message
![2024-04-02 06_51_52-main ts - platform_api - Visual Studio Code](https://github.com/BeeQuantAI/platform_api/assets/80236130/6d3c4033-3d71-4d91-9184-25ea6124aa6d)

then I added add this code snippet into  '.eslintrc.js', then error message disappear
    'prettier/prettier': [
      'error',  
      {
        endOfLine: 'auto',   
      },
    ],

**Comment by Chris-Wang** [comment]
Emm... that looks interesting, I will setup a windows machine to double check with that, thanks, Ray!

**Comment by Chris-Wang** [comment]
Solution post on: https://www.notion.so/Resolve-Line-Breaks-issue-in-Windows-25923567600e487a85dc2670ec6fd723?pvs=4
