### ISSUE TITLE
yarn start: Cannot find type definition file for 'mime' on windows 11. 

### ISSUE THREAD

**Issue by hulinpiao** [BeeQuantAI/platform_api#5]
When I followed the instructions in the readme.txt to set up my environment and tried to run the service using `yarn start` or `yarn start:dev`, it didn't work properly and showed following error message: 

```
Eric@Desktop-Eric MINGW64 ~/JRDevops12/platform_api (dev)
$ yarn start:dev
[11:42:15 pm] Starting compilation in watch mode...

error TS2688: Cannot find type definition file for 'mime'.
  The file is in the program because:
    Entry point for implicit type library 'mime'

[11:42:27 pm] Found 1 error. Watching for file changes.


Eric@Desktop-Eric MINGW64 ~/JRDevops12/platform_api (dev)
$ yarn start
yarn run v1.22.19
$ nest start
error TS2688: Cannot find type definition file for 'mime'.
  The file is in the program because:
    Entry point for implicit type library 'mime'

Found 1 error(s).

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by hulinpiao** [comment]
I'm not very familiar with backend tech stacks and would greatly appreciate it if someone could provide a perfect solution.

But my temp solution was running following command : `yarn add @types/mime --dev` to add the 'mime' library to the package.json file. After adding it, I confirmed that the service started working correctly.

**Comment by CharlesZhao27** [comment]
same issue here on Mac, I still not able to label why this is happening.

can be resolved by adding following lines into your `package.json` file:

```
"resolutions": {
    "@types/mime": "3.0.4"
 }
```

similar issue can be found here:  #https://github.com/firebase/firebase-admin-node/issues/2512

**Comment by hulinpiao** [comment]
issue has been fixed and merged via the[ MR.](https://github.com/BeeQuantAI/platform_api/pull/6)
close the issue.
