### ISSUE TITLE
Question: Potentially need a yarn.lock file?

### ISSUE THREAD

**Issue by captainboris** [BeeQuantAI/platform_api#7]
Hey guys I'm trying to write a dockerfile for this application, but noticed that we don't have a yarn.lock file yet. Ideally I will need to copy this file to docker image to lock dependency. Are we planning to have this sometime in the future?

**Comment by Chris-Wang** [comment]
I think that's a valid request, I will remove yarn.lock from gitignore, and have you to help me to test it in a branch.

**Comment by Chris-Wang** [comment]
Issue resolved by adding yarn.lock
